Models/Job.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Platform.Models
{
    public class Job
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public int Vacancies { get; set; }
        public double MinPay { get; set; }
        public double MaxPay { get; set; }
        public int MinYearExperience { get; set; }
        public int MaxYearExperience { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public JobTypes JobTypeID { get; set; }
        public DateTime? ExpireDate { get; set; }
        public string JobDescription { get; set; }
        public string Skills { get; set; }
        public string Education { get; set; }
        public DateTime UpdatedAt { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

Models/JobTypes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Platform.Models
{
    public enum JobTypes
    {
        [Display(Name = "Part Time")]
        PartTime = 1,
        [Display(Name = "Full Time")]
        FullTime = 2,
        [Display(Name = "Internship")]
        Internship = 3,
        [Display(Name = "Contract")]
        Contract = 4,
        [Display(Name = "Remote")]
        Remote = 5
    }
}

Models/ViewModel/JobViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Platform.Models.ViewModel
{
    public class JobViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Job title cannot be blank")]
        [Display(Name = "Job Title")]
        public string JobTitle { get; set; }
        [Required(ErrorMessage = "Enter Price!")]
        [Range(1, int.MaxValue, ErrorMessage = "Invalid Input")]
        public int Vacancies { get; set; }
        [Required(ErrorMessage = "Category Select a Category!")]
        [DisplayName("Category")]
        public int CategoryId { get; set; }
        public IEnumerable<CategoryViewModel> Categories { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Select a correct Job Type")]
        [Display(Name = "Job Type")]
        public JobTypes JobTypesId { get; set; }
        [DisplayName("Expiry Date")]
        [DataType(dataType: DataType.DateTime)]
        public DateTime? ExpireDate { get; set; }
        [Required(ErrorMessage = "Give A Description!")]
        [DisplayName("Job Description")]
        [DataType(DataType.MultilineText)]
        public string JobDescription { get; set; }
        [Required(ErrorMessage = "Give A Skills!")]
        [DisplayName("Required Knowledge, Skills, and Abilities")]
        [DataType(DataType.MultilineText)]
        public string Skills { get; set; }
        [Required(ErrorMessage = "Give A Education!")]
        [DisplayName("Education Qualification")]
        [DataType(DataType.MultilineText)] 
        public string Education { get; set; }
        [Required]
        [Range(20000.99, double.MaxValue)]
        public double MinPay { get; set; }

        public double MaxPay { get; set; }
        [Required]
        public int MinYearExperience { get; set; }
        [Range(1, 50)]
        public int MaxYearExperience { get; set; }
    }
}

Controllers/JobsController.cs
using AutoMapper;
using Platform.Models;
using Platform.Models.ViewModel;
using Platform.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Platform.Controllers
{
    public class JobsController : Controller
    {
        private readonly IDashboardRepository _dashboard;
        private readonly IJobRepository _job;
        public JobsController(IDashboardRepository dashboard, IJobRepository job)
        {
            _dashboard = dashboard;
            _job = job;
        }
        // GET: Jobs
        public ActionResult Index()
        {
            var jobDb = _job.Jobs();
            return View(jobDb);
        }
        public ActionResult JobDetails(int id)
        {
            var job = Mapper.Map<Job, JobViewModel>(_job.GetById(id));
            return View(job);
        }
        public ActionResult CreateJob()
        {
            var model = new JobViewModel
            {
                Categories = Mapper.Map<IEnumerable<Category>, IEnumerable<CategoryViewModel>>(_dashboard.GetAll())
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateJob(JobViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _job.CreateJob(model);
                if (result)
                {
                    TempData["jobMsg"] = "Job Successfully Added";
                    return RedirectToAction("CreateJob");
                }
                else
                {
                    TempData["jobMsg"] = "Job cannot be added";
                    return RedirectToAction("CreateJob");
                }
                
            }
            else
            {
                ModelState.AddModelError(string.Empty, "An Internal Error Occured");
                model.Categories = Mapper.Map<IEnumerable<Category>, IEnumerable<CategoryViewModel>>(_dashboard.GetAll());
                return View("CreateJob",model);
            }
        }
    }
}

Views/Jobs/CreateJob.cshtml
@model Platform.Models.ViewModel.JobViewModel
@{
    ViewBag.Title = "CreateJob";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="page-title-area">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="page-title-text">
                    <h2>Post A Job</h2>
                    <ul>
                        <li>
                            <a href="index-2.html">Home</a>
                        </li>
                        <li>
                            <i class="icofont-simple-right"></i>
                        </li>
                        <li>Post A Job</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="post-job-area pt-100">
    <div class="container">
        <div class="post-job-item">
            @using (Html.BeginForm("CreateJob", "Jobs", null, FormMethod.Post, new { enctype = "multipart/form-data", accept_charset = "utf-8" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="post-job-heading">
                    <h2>Post Your Job</h2>
                </div>
                if (TempData["jobMsg"] != null)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @TempData["jobMsg"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { })
                            @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control", placeholder = "UX/UI Designer" } })
                            @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { })
                            <div class="job-category-area">
                                @Html.DropDownListFor(m => m.CategoryId, new SelectList(Model.Categories, "Id", "CategoryName"), "Select Job Category", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MinPay, htmlAttributes: new { })
                            @Html.EditorFor(model => model.MinPay, new { htmlAttributes = new { @class = "form-control", placeholder = "$0.00" } })
                            @Html.ValidationMessageFor(model => model.MinPay, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxPay, htmlAttributes: new { })
                            @Html.EditorFor(model => model.MaxPay, new { htmlAttributes = new { @class = "form-control", placeholder = "$0.00" } })
                            @Html.ValidationMessageFor(model => model.MaxPay, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MinYearExperience, htmlAttributes: new { })
                            @Html.EditorFor(model => model.MinYearExperience, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MinYearExperience, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxYearExperience, htmlAttributes: new { })
                            @Html.EditorFor(model => model.MaxYearExperience, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MaxYearExperience, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Vacancies, htmlAttributes: new { })
                            @Html.EditorFor(model => model.Vacancies, new { htmlAttributes = new { @class = "form-control", placeholder = "Number of Vacancies" } })
                            @Html.ValidationMessageFor(model => model.Vacancies, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ExpireDate, htmlAttributes: new { })
                            @Html.EditorFor(model => model.ExpireDate, new { htmlAttributes = new { @class = "form-control", placeholder = "MM/DD/YYYY" } })
                            @Html.ValidationMessageFor(model => model.ExpireDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobTypesId, htmlAttributes: new { })
                            @Html.EnumDropDownListFor(m => m.JobTypesId, "-- Select JobType --", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.JobTypesId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobDescription, htmlAttributes: new { })
                            @Html.TextAreaFor(m => m.JobDescription, new { @class = "form-control", @id = "your_message", rows = 8 })
                            @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Skills, htmlAttributes: new { })
                            @Html.TextAreaFor(m => m.Skills, new { @class = "form-control", @id = "your_message", rows = 8 })
                            @Html.ValidationMessageFor(model => model.Skills, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Education, htmlAttributes: new { })
                            @Html.TextAreaFor(m => m.Education, new { @class = "form-control", @id = "your_message", rows = 8 })
                            @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn create-ac-btn">Post</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Jobs/Index.cshtml
@model IEnumerable<Platform.Models.Job>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Dashboard/_DashboardLayout.cshtml";
}

<div class="content">
    <div class="container">
        <div class="page-title">
            <h3>
                All Jobs
                <a href="@Url.Action("CreateJob", "Jobs")" class="btn btn-sm btn-outline-primary float-right"><i class="fa fa-user-shield"></i> Add New</a>
            </h3>
        </div>
        <div class="box box-primary">
            <div class="box-body">
                <table width="100%" class="table table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.JobTitle)</th>
                            <th>@Html.DisplayNameFor(model => model.Vacancies)</th>
                           <th>@Html.DisplayNameFor(model => model.Category.CategoryName)</th>
                            <th>@Html.DisplayNameFor(model => model.JobTypeID)</th>
                            <th>@Html.DisplayNameFor(model => model.MinPay)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.JobTitle</td>
                            <td>@item.Vacancies</td>
                            <td>@item.Category.CategoryName</td>
                            <td>@item.JobTypeID</td>
                            <td>@item.MinPay</td>
                            <td class="text-right">
                                <a href="@Url.Action("EditJob", "Jobs", new { id = item.Id})" class="btn btn-outline-info btn-rounded"><i class="fas fa-pen"></i></a>
                                <a href="@Url.Action("JobDetails", "Jobs", new { id = item.Id})" class="btn btn-outline-success btn-rounded"><i class="fas fa-eye-slash"></i></a>
                                <a href="@Url.Action("DeleteJob", "Jobs", new { id = item.Id})" class="btn btn-outline-danger btn-rounded"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Jobs/JobDetails.cshtml
@model Platform.Models.ViewModel.JobViewModel
@{
    ViewBag.Title = "JobDetails";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<div class="page-title-area">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="page-title-text">
                    <h2>Job Details</h2>
                    <ul>
                        <li>
                            <a href="index-2.html">Home</a>
                        </li>
                        <li>
                            <i class="icofont-simple-right"></i>
                        </li>
                        <li>Job Details</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="job-details-area pt-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job-details-item">
                    <div class="job-description">
                        <h2>Job Description</h2>
                        <p>@Model.JobDescription</p>
                    </div>
                    <div class="job-knowledge">
                        <h2>Required Knowledge, Skills, and Abilities</h2>
                        <ul>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Hand On experience with Wordpress
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Better knowledge of front-end technologies, including HTML5, CSS3, JavaScript, jQuery
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Belief – believing in yourself and those around you
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Experience designing and developing responsive design websites
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Ability to convert comprehensive layout and wireframes into working HTML pages
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Strong understanding of PHP back-end development
                            </li>
                        </ul>
                    </div>
                    <div class="job-knowledge">
                        <h2>Education Qualification</h2>
                        <ul>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Any Graduattion Degree(13th Pass) (Preferred)
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Advanced degree or equivalent experience in graphic and web design
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                2 or more years of professional design experience
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Direct response email experience
                            </li>
                            <li>
                                <i class="icofont-hand-drawn-right"></i>
                                Ecommerce website design experience
                            </li>
                        </ul>
                    </div>
                    <div class="text-center">
                        <a class="job-details-btn" href="create-account.html">Apply Now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job-details-item">
                    <div class="job-overview">
                        <h3>Overview</h3>
                        <ul>
                            <li>
                                <i class="icofont-dollar"></i>
                                <p>Offered Salary</p>
                                <span>$10k-$150k</span>
                            </li>
                            <li>
                                <i class="icofont-users-alt-3"></i>
                                <p>Gender</p>
                                <span>Male</span>
                            </li>
                            <li>
                                <i class="icofont-badge"></i>
                                <p>Experince</p>
                                <span>2 Years</span>
                            </li>
                            <li>
                                <i class="icofont-graduate"></i>
                                <p>Qualification</p>
                                <span>Master Degree</span>
                            </li>
                        </ul>
                    </div>
                    <div class="job-overview job-company">
                        <h3>Company Address</h3>
                        <ul>
                            <li>
                                <i class="icofont-location-pin"></i>
                                <span>4th Floor, 408 No Chamber</span>
                            </li>
                            <li>
                                <i class="icofont-ui-call"></i>
                                <a href="tel:+07554332322">Call : +07 554 332 322</a>
                            </li>
                            <li>
                                <i class="icofont-ui-email"></i>
                                <a href="https://templates.hibootstrap.com/cdn-cgi/l/email-protection#1a727f7676755a7d7b78767f34797577"><span class="__cf_email__" data-cfemail="660e030a0a09260107040a034805090b">[email&#160;protected]</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>