Models/Test.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Platform.Models
{
    public class Test
    {
        public int Id { get; set; }
        public string TestName { get; set; }
    }
}

Models/ViewModel/TestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Platform.Models.ViewModel
{
    public class TestViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Enter a Test")]
        [Display(Name = "Test Name")]
        public string TestName { get; set; }
        [DataType(DataType.Upload)]
        [Display(Name = "Upload Image")]
        [Required(ErrorMessage = "Please choose file to upload. ")]
        public string FilePath { get; set; }
        public HttpPostedFileBase File { get; set; }
        
    }
}

Controllers/TestController.cs
using Platform.Models;
using Platform.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using File = Platform.Models.File;

namespace Platform.Controllers
{
    public class TestController : Controller
    {
        private readonly ITestRepository _test;
        public TestController(ITestRepository test)
        {
            _test = test;
        }
        // GET: Test
        public ActionResult Index()
        {
            var test = _test.GetAll();
            return View(test);
        }
        [HttpGet]
        public ActionResult AddTest()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddTest(Test test)
        {
            return View();
        }
        public ActionResult UploadSingleFile()
        {
            return View();
        }
        public ActionResult UploadMultipleFiles()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadSingleFile(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                string filename = Path.GetFileNameWithoutExtension(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                string filePath = "~/Images/" + filename;
                var path = Server.MapPath(filePath);
                file.SaveAs(path);
                // save to file database if need be
                var file1 = new File
                {
                    FileName = filename,
                    FilePath = filePath
                };
                //insert file
                _test.Save();

            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadMultipleFiles(IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string filename = Path.GetFileNameWithoutExtension(file.FileName);
                    string extension = Path.GetExtension(file.FileName);
                    filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                    string filePath = "~/Images/" + filename;
                    var path = Server.MapPath(filePath);
                    file.SaveAs(path);
                    // save to file database if need be
                    var file1 = new File
                    {
                        FileName = filename,
                        FilePath = filePath
                    };
                    //save to db
                   
                }
                _test.Save();
            }
            return View();
        }
    }
}

Views/Test/AddTest.cshtml
@model Platform.Models.ViewModel.TestViewModel

@{
    ViewBag.Title = "AddTest";
    Layout = "~/Views/Dashboard/_DashboardLayout.cshtml";
}

<h2>AddTest</h2>

@using (Html.BeginForm("AddTest", "Test", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Test</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TestName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" id="image" name="File" accept="image/*"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Test/Index.cshtml
@model IEnumerable<Platform.Models.Test>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Dashboard/_DashboardLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TestName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TestName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Test/UploadMultipleFiles.cshtml
@{
    ViewBag.Title = "UploadMultipleFiles";
    Layout = null;
}

<h2>UploadMultipleFiles</h2>
@using (Html.BeginForm("UploadMultipleFiles", "Test", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <label for="file">Upload Image:</label>
    <input type="file" name="files" id="files" multiple />
    <input type="submit" value="Upload" />
}

Views/Test/UploadSingleFile.cshtml
@{
    ViewBag.Title = "UploadSingleFile";
    Layout = null;
}

<h2>UploadSingleFile</h2>

@using (Html.BeginForm("UploadSingleFile", "Test", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <label for="file">Upload Image:</label>
    <input type="file" name="file" id="file" />
    <input type="submit" value="Upload" />
}